### ISSUE TITLE
Feature request: Cookie domain rewrite

### ISSUE THREAD

**Issue by kenrick95** [lwsjs/rewrite#1]
When we rewrite URL that has a response to set a cookie (i.e. response has `set-cookie` header), sometimes, the response will specify to set the cookie in the remote domain, hence locally, the expected cookie isn't present. 

This feature request is similar to [`cookieDomainRewrite` option use case at `node-http-proxy` library (more details at its PR)](https://github.com/nodejitsu/node-http-proxy/pull/1009). I hope you could consider it. Thanks for your time 😁

**Comment by 75lb** [comment]
Thanks, this sounds useful - I will look into it. 

In the meantime, please take a look [at this wiki page](https://github.com/lwsjs/local-web-server/wiki/Using-middleware), hopefully it contains enough information for you to try adding the feature yourself.

**Comment by kenrick95** [comment]
Do you have documents on how to get started to contribute to this repos? Seems I can't find the Contributing guideline. I have questions like, which repo to fork and how to set it up locally. Thanks

---

Anyway, for my use case, I have written at my application a custom middleware just to handle that (only to remove the "domain" part of a cookie) 😁

**Comment by 75lb** [comment]
Glad you have solved it with a custom middleware. There are no special rules regarding contributing, it's just the standard process - fork a project, edit it locally, submit a PR.

If you want to share your middleware, publish it to npm. It can then be [used as middleware](https://github.com/lwsjs/local-web-server/wiki/Using-middleware) by any project.

**Comment by gavenkoa** [comment]
https://github.com/chimurai/http-proxy-middleware supports `option.cookieDomainRewrite` to exactly this purpose. That's why I migrated to Connect/Express.js middlware. `lws` lags behind a century, it is better not to waste time with unsupported tool.
