### ISSUE TITLE
Consider making rewrite domain-aware

### ISSUE THREAD

**Issue by WORMSS** [lwsjs/rewrite#13]
Hello, I think I already know the answer to this after a brief play with cli, and a quick look through the code, but it never hurts to ask.

```sh
npx lws-rewrite "https://a.mydomain.com/(.+)" "http://localhost:8081/a/$1" "https://a.mydomain.com/test"
```

I was hoping to see
```sh
http://localhost:8081/a/test
```
but I was greeted with the lovely error message of
```sh
C:\WINDOWS\system32>npx lws-rewrite "https://a.mydomain.com/(.+)" "http://localhost:8081/a/$1" "https://a.mydomain.com/test"
C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\node_modules\path-to-regexp\dist\index.js:48
                throw new TypeError("Missing parameter name at ".concat(i));
                ^

TypeError: Missing parameter name at 5
    at lexer (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\node_modules\path-to-regexp\dist\index.js:48:23)
    at parse (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\node_modules\path-to-regexp\dist\index.js:98:18)
    at stringToRegexp (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\node_modules\path-to-regexp\dist\index.js:329:27)
    at pathToRegexp (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\node_modules\path-to-regexp\dist\index.js:407:12)
    at Object.getTargetUrl (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\lib\util.js:21:14)
    at Object.<anonymous> (C:\Users\CRichardson\AppData\Roaming\nvm\v19.6.0\node_modules\lws-rewrite\bin\cli.js:9:20)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)

Node.js v19.6.0
```

So, yes, I can see by the examples, you guys are expecting first and third params to be the path from server, and not a path including server..

But You never know, there could be some secret option I was not able to find, so thought best to ask.

**Comment by 75lb** [comment]
Are you on mac/linux? If so, use single quotes as bash/shell will perform parameter expansion otherwise.. try 

```
npx lws-rewrite 'https://a.mydomain.com/(.+)' 'http://localhost:8081/a/$1' 'https://a.mydomain.com/test'
```

**Comment by WORMSS** [comment]
![Screenshot_20230207-203048](https://user-images.githubusercontent.com/1384537/217358350-0be088e5-4702-42ce-b144-0a050017ad41.png)

Windows.

**Comment by 75lb** [comment]
the three input params should be paths, not full URLs.. except param 2 ("to" address) - that can be a full URL if you explicitly redirecting to a new host (e.g. localhost in your case)

```
$ npx lws-rewrite '/(.+)' 'http://localhost:8081/a/$1' '/test/hello'
http://localhost:8081/a/test/hello
```

**Comment by WORMSS** [comment]
So it can't be done then?

My ultimate goal is to have
https&#58;//**a**.mydomain.com/(.\*) -> http&#58;//localhost&#58;**8081**/$1
https&#58;//**b**.mydomain.com/(.\*) -> http&#58;//localhost&#58;**8082**/$1
https&#58;//**c**.mydomain.com/(.\*) -> http&#58;//localhost&#58;**8083**/$1
https&#58;//**d**.mydomain.com/(.\*) -> http&#58;//localhost&#58;**8084**/$1
https&#58;//**e**.mydomain.com/(.\*) -> http&#58;//localhost&#58;**8085**/$1

I knew lws-redirect wouldn't work for this so I wrote myself a reverse proxy from scratch,
but it is cumbersome and when I just happened to come across the lws-rewrite plugin and thought.. OOH... MAYBE...

This is why I was asking if there was a option that I was unaware of to make it domain aware, and not limited to just paths.

**Comment by 75lb** [comment]
so requests to a, b, c, d and e.mydomain.com are all forwarded to one `ws` instance? So you have a DNS Alias record something like this? 

```
A *.mydomain.com 192.168.1.1
```

lws-rewrite uses [path-to-regexp](https://github.com/pillarjs/path-to-regexp) internally (from the express project), i don't think it's domain-aware - it operates on the path portion only.. I will need to take a deeper look into this..

**Comment by WORMSS** [comment]
Yes, I have all subdomains directed towards a single IP.

I have very many internal servers all running different SPAs or other type of testing servers.
All these servers run on various ports, usually around the 8080 and increasing.

And I have 2 servers that are run on port 80
```sh
ws --port 80 --stack lws-redirect --redirect "http -> https"
```
And port 443.. This is where I would LOVE to be able to use
```sh
ws --port 443 --https --key **** --cert **** --stack lws-rewrite --rewrite <all the stuffs>
```

But instead I got a server that loops through a list of domains and ports and basically does
```js
const config = [
  ['a.mydomain.com', 8080],
  ['b.mydomain.com', 8081],
  ['c.mydomain.com', 8082],
  ['d.mydomain.com', 8083],
  ['e.mydomain.com', 8084],
];
return (req, res) => {
  for (const [domain, port] of config) {
    const originalURL = new URL(req.url ?? '', `https://${req.headers.host ?? 'localhost'}`);

    if (originalURL.host !== domain) {
      continue;
    }

    const requestURL = new URL(originalURL);
    requestURL.host = 'localhost';
    requestURL.port = String(port);
    requestURL.protocol = 'http';

    const options = {
      ...req,
      headers: Object.fromEntries(Object.entries(req.headers)), // I don't remember why, but I had to
    };

    const requestConnection = require('http')
      .request(requestURL, options, (response) => {
        res.writeHead(response.statusCode ?? 500, response.headers);
        response.pipe(res);
      })
      .on('error', (err) => {
        res.writeHead(500);
        res.write(String(err));
        res.end();
      });
    req.pipe(requestConnection);
  }
}
```

Not the greatest in the world.. but it's keeping me afloat for now..

**Comment by WORMSS** [comment]
@75lb 
I was just wondering how much "considering" has happened since last we talked

**Comment by 75lb** [comment]
I didn't assign this as high priority since you're the only one to mention the issue so far plus you had a temporary workaound..

**Comment by 75lb** [comment]
Closing.. I'm not saying it is not useful but it is beyond the scope of lws-rewrite.

**Comment by 75lb** [comment]
> const config = [
>   ['a.mydomain.com', 8080],
>   ['b.mydomain.com', 8081],
>   ['c.mydomain.com', 8082],
>   ['d.mydomain.com', 8083],
>   ['e.mydomain.com', 8084],
> ];

Just noticed [this example](https://github.com/chimurai/http-proxy-middleware?tab=readme-ov-file#router-objectfunction), reminded me of what you were trying to achieve..
