### ISSUE TITLE
`https-proxy-agent` v2.x includes high severity vulnerability

### ISSUE THREAD

**Issue by admvx** [lwsjs/rewrite#8]
When installing `lws-rewrite` via `local-web-server` NPM reports a high severity vulnerability in `https-proxy-agent` that is fixed in v3.x. Details about the securty issue: https://npmjs.com/advisories/1184

Would it be possible to upgrade to v3? Thanks!

**Comment by 75lb** [comment]
done, please reinstall to pick up the change.. thanks. 👍

**Comment by admvx** [comment]
🔥 Amazing, thank you!
